baseURL: https://px-study.netlify.app
languageCode: en-us
title: Peixin 的杂七杂八
theme: "hugo-theme-mini"

# for exampleSite only, you may need to delete the line: `themesDir: ../../` 

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  #github: your-github-link
  #twitter: 敬请期待
  #stackoverflow: your-github-link
  facebook: https://www.facebook.com/profile.php?viewas=100000686899395&id=100004244896990
  wechat: images/wch.png
  instagram: https://www.instagram.com/peixinnnnnnnnn/


# Site parameters
params:
  # Site Author
  author: Peixin
  # Author biography
  bio:  吾生也有涯，而知也无涯 
  # Site Description, used in HTML meat
  description: My Blog
  enableRSS: false
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true

  # Optional
  home: '主页' # Default: Home
  about: '关于我' # Default: About
  archive: '文章列表' # Default: Archive
  tags: '按标签' # Default: Tags
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '' # Default: © Copyright 2021 ❤️ author
  title404: '555 找不到页面啦' # Default: 404 - Page Not Found
  subtitle404: '有问题可以直接联系px哦' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project

